### ISSUE TITLE
Migrate to Habitat

### ISSUE THREAD

**Issue by Dids** [Didstopia/rust-server#20]
Migrate to [Habitat](https://habitat.sh) which will allow us to export to Docker, bare metal, virtual machines etc. while the server stays the same across all systems and environments.

**Comment by predominant** [comment]
This is an awesome idea. With a ton of hacks, I was able to get steamcmd working under habitat, but I think it needs proper support with the 32bit libs being compiled and patched in properly.

**Comment by predominant** [comment]
@Dids I've been doing a lot of work on Habitat lately. Some core-plans commits, and had a nice visit from the Habitat engineering team. I think this is possible, but we'd have to build (or otherwise ship) the 32bit libs for 64 bit systems separately. This is due to the steam client being 32bit.

This is normally done with a package from the OS, and I'm certain this would be useful to more applications than just the steam client. Leave it with me, and I'll see what I can come up with!

**Comment by Dids** [comment]
@predominant Sounds good to me!

**Comment by predominant** [comment]
Good enough. I still don't have 32bit libs available on Habitat.

**Comment by Dids** [comment]
There are talks about Valve finally dropping 32-bit support from Steam, which I'm hoping applies to all platforms. If it ever gets there, feel free to reopen. Regarding the "stale bot", I figured this repo was getting enough traction to warrant one, just to keep abandoned or forgotten issues in check.
