### ISSUE TITLE
RCON leaking data externally

### ISSUE THREAD

**Issue by Hardcore-fs** [Didstopia/rust-server#40]
it seems that "rcon"  is leaking data to 
 www.battlemetrics.com
all details of the players  online are exposed, including the playing time.

is there anyway to block this information, it seems it is default for the basic container.

**Comment by Dids** [comment]
The Steam query port (iirc it's 28016/udp by default, RCON uses same port but TCP) is designed by the developers to allow public server querying, and while you could simply not expose that port, I'm fairly certain your server would then disappear from the in-game server list. To reiterate: this is by design, and it's public information, which Battlemetrics simply utilizes. Same applies to a lot of different Steam games.
