### ISSUE TITLE
Can't acces any rcon command

### ISSUE THREAD

**Issue by neolectron** [Didstopia/rust-server#6]
Hi,

when i'm trying to run any rcon command with :
`docker exec rust rcon ANYCOMMAND`
I got this :
```
{ Error: connect ECONNREFUSED 127.0.0.1:28016
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 28016 }
```

When i'm trying to login to the webrcon panel, i've got
`Connection was closed - Error 1006`

When ingame console i type rcon.login
i've got "invalid command"

here's my startscript : 
```
docker run -it --name rust \
    -p 28015:28015 \
    -p 28015:28015/udp \
    -p 28016:28016 \
    -p 8080:8080 \
    -v /Serv/rust/rust:/steamcmd/rust \
    --env-file /Serv/rust/rust.env \
    didstopia/rust-server
```

here's my env-file
```
RUST_SERVER_NAME=NiceNice
RUST_SERVER_DESCRIPTION=oui
RUST_SERVER_URL=blabla.com
RUST_RCON_WEB=1
RUST_RCON_PASSWORD=password
RUST_UPDATE_CHECKING=1
RUST_OXIDE_ENABLED=0
RUST_OXIDE_UPDATE_ON_BOOT=1
```

is there something i did wrong ?
(cfg folder is empty [suspicious])

thx

**Comment by Dids** [comment]
This should definitely be working, just tested it with the default options, and the command `docker exec rust-server rcon status` worked fine for me, returning the overall server status.

You're certain the server is running?

Try modifying your env-file so it's just this:
```
RUST_SERVER_NAME=NiceNice
RUST_SERVER_DESCRIPTION=oui
RUST_SERVER_URL=blabla.com
RUST_RCON_PASSWORD=password
```

From what I can tell, your issue comes from not being able to connect to the RCON port on 28016, which could be caused by a number of things. Can you see any errors in your Rust server output when you try to connect/execute RCON commands? Do you have another server running on the same machine? Are you running `docker run ...` and `docker exec ...` on the same machine?

**Comment by neolectron** [comment]
Nope, still hot the same error with your envfile..

Check-out this screenshot : https://drive.google.com/file/d/0B5SXMwnKomXSQWdTREFzdWRueXc/view?usp=drivesdk
 
Also note that ingame everything looks fine.
Note that i waited the boot time to type my `docker exec` command.
Its just about the rcon server imo.
Did I forget something in my startscript ? (Ports etc...)

(I have no other stuff using that port.)

**Comment by neolectron** [comment]
PS : just checked something. I can't find the `rcon.ip=0.0.0.0` instruction on your défault start command. I'll try to add it today. I'll come back to you after.

**Comment by Dids** [comment]
Yeah, `rcon.ip` isn't required, because it's set to `0.0.0.0` by default.

How about your firewall? Could it be blocking/not allowing connections on 28016?

You could also try adding `--net=host` right after `run` in your `docker run ...` command, as this will bind the networking (ports) to the server itself, and not just use port forwarding.

**Comment by neolectron** [comment]
Same with `--net=host`.
if you want more details we can meet on discord and i'll give you ssh access.
because i really think i'm doing well. I had lots of gameserver and I have a good knowledge in devops...

ps : I'm on debian8.

**Comment by neolectron** [comment]
ok, it's because the password was "password" and rust replace with sed/ the password by "****" in the console to not show it. but it aslo replaced rcon.password by "rcon.****"
chaging my pw to something else, fixed the bug.
